In [1]:
def verify_input(p):
    return p % 4 == 3

In [2]:
with open('ieeja.txt') as file:
    try:
        p = int(file.readline())
        assert verify_input(p)
    except (ValueError, AssertionError):
        print('p is not defined or incorrect')

In [1]:
import math


def invertRow(row):
    rowInv = row[:]
    for i in range(len(row)):
        if row[i] > 0:
            rowInv[i] = -1
        else:
            rowInv[i] = 1
    return rowInv

def scaleMatrix(matrix):
    resultMatrix = []

    for i in range(len(matrix)):
        resultMatrix += [matrix[i]+matrix[i]]
        
    for i in range(len(matrix)):
        resultMatrix += [matrix[i]+invertRow(matrix[i])]

    return resultMatrix

def buildHadamard():
    matrix = [[1]]
    matrix_length = 2

    for _ in range(int(math.log2(matrix_length))):
        matrix = scaleMatrix(matrix)

    return matrix 

def save_results(matrix):
    with open('izeja.txt', 'w') as file:
        file.writelines([f"{' '.join([str(i) for i in matrix[line]])}\n" for line in range(len(matrix))])
        

matrix = buildHadamard()
import numpy as np
print(np.asarray(matrix))
# save_results(matrix)

[[ 1  1]
 [ 1 -1]]


In [ ]:
# Ieejas dati:

    p = 3

# Izējas dati:

    Matrica ar lielumu (p + 1)^2 = 16

    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
    1 -1 1 -1 1 -1 1 -1 1 -1 1 -1 1 -1 1 -1
    1 1 -1 -1 1 1 -1 -1 1 1 -1 -1 1 1 -1 -1
    1 -1 -1 1 1 -1 -1 1 1 -1 -1 1 1 -1 -1 1
    1 1 1 1 -1 -1 -1 -1 1 1 1 1 -1 -1 -1 -1
    1 -1 1 -1 -1 1 -1 1 1 -1 1 -1 -1 1 -1 1
    1 1 -1 -1 -1 -1 1 1 1 1 -1 -1 -1 -1 1 1
    1 -1 -1 1 -1 1 1 -1 1 -1 -1 1 -1 1 1 -1
    1 1 1 1 1 1 1 1 -1 -1 -1 -1 -1 -1 -1 -1
    1 -1 1 -1 1 -1 1 -1 -1 1 -1 1 -1 1 -1 1
    1 1 -1 -1 1 1 -1 -1 -1 -1 1 1 -1 -1 1 1
    1 -1 -1 1 1 -1 -1 1 -1 1 1 -1 -1 1 1 -1
    1 1 1 1 -1 -1 -1 -1 -1 -1 -1 -1 1 1 1 1
    1 -1 1 -1 -1 1 -1 1 -1 1 -1 1 1 -1 1 -1
    1 1 -1 -1 -1 -1 1 1 -1 -1 1 1 1 1 -1 -1
    1 -1 -1 1 -1 1 1 -1 -1 1 1 -1 1 -1 -1 1

In [3]:
def invertRow(row):
    rowInv = row[:]
    for i in range(len(row)):
        if row[i] > 0:
            rowInv[i] = -1
        else:
            rowInv[i] = 1
    return rowInv

def scaleMatrix(matrix):
    resultMatrix = []

    for i in range(len(matrix)):
        resultMatrix += [matrix[i]+matrix[i]]
        
    for i in range(len(matrix)):
        resultMatrix += [matrix[i]+invertRow(matrix[i])]

    return resultMatrix

def mainCode():
    matrix = [[1]]
    dim = 1

    while (dim < 12):
        matrix = scaleMatrix(matrix)
        dim *= 2

    return matrix 

        
matrix = mainCode()
print(np.asarray(matrix))
#verifyOrthogonal(matrix) #test

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1]
 [ 1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1]
 [ 1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1]
 [ 1  1  1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1]
 [ 1 -1  1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1]
 [ 1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1]
 [ 1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1  1 -1]
 [ 1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 1 -1  1 -1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1]
 [ 1  1 -1 -1  1  1 -1 -1 -1 -1  1  1 -1 -1  1  1]
 [ 1 -1 -1  1  1 -1 -1  1 -1  1  1 -1 -1  1  1 -1]
 [ 1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1]
 [ 1 -1  1 -1 -1  1 -1  1 -1  1 -1  1  1 -1  1 -1]
 [ 1  1 -1 -1 -1 -1  1  1 -1 -1  1  1  1  1 -1 -1]
 [ 1 -1 -1  1 -1  1  1 -1 -1  1  1 -1  1 -1 -1  1]]
